//
// Generated file, do not edit! Created by opp_msgtool 6.1 from stack/rlc/am/packet/LteRlcAmSdu.msg.
//

#ifndef __SIMU5G_LTERLCAMSDU_M_H
#define __SIMU5G_LTERLCAMSDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class LteRlcAmSdu;

}  // namespace simu5g

#include "stack/rlc/packet/LteRlcSdu_m.h" // import stack.rlc.packet.LteRlcSdu


namespace simu5g {

/**
 * Class generated from <tt>stack/rlc/am/packet/LteRlcAmSdu.msg:17</tt> by opp_msgtool.
 * <pre>
 * class LteRlcAmSdu extends LteRlcSdu
 * {
 * }
 * </pre>
 */
class LteRlcAmSdu : public ::LteRlcSdu
{
  protected:

  private:
    void copy(const LteRlcAmSdu& other);

  protected:
    bool operator==(const LteRlcAmSdu&) = delete;

  public:
    LteRlcAmSdu();
    LteRlcAmSdu(const LteRlcAmSdu& other);
    virtual ~LteRlcAmSdu();
    LteRlcAmSdu& operator=(const LteRlcAmSdu& other);
    virtual LteRlcAmSdu *dup() const override {return new LteRlcAmSdu(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteRlcAmSdu& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteRlcAmSdu& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::LteRlcAmSdu *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::LteRlcAmSdu*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_LTERLCAMSDU_M_H

