//
// Generated file, do not edit! Created by opp_msgtool 6.1 from stack/rlc/LteRlcDefs.msg.
//

#ifndef __SIMU5G_LTERLCDEFS_M_H
#define __SIMU5G_LTERLCDEFS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {


}  // namespace simu5g

// cplusplus {{
#include "stack/rlc/LteRlcDefs.h"
// }}


namespace simu5g {


}  // namespace simu5g


namespace omnetpp {

inline any_ptr toAnyPtr(const simu5g::RlcFragDesc *p) {return any_ptr(p);}
template<> inline simu5g::RlcFragDesc *fromAnyPtr(any_ptr ptr) { return ptr.get<simu5g::RlcFragDesc>(); }
inline any_ptr toAnyPtr(const simu5g::RlcWindowDesc *p) {return any_ptr(p);}
template<> inline simu5g::RlcWindowDesc *fromAnyPtr(any_ptr ptr) { return ptr.get<simu5g::RlcWindowDesc>(); }
inline any_ptr toAnyPtr(const simu5g::MrwDesc *p) {return any_ptr(p);}
template<> inline simu5g::MrwDesc *fromAnyPtr(any_ptr ptr) { return ptr.get<simu5g::MrwDesc>(); }
inline any_ptr toAnyPtr(const simu5g::RlcUmRxWindowDesc *p) {return any_ptr(p);}
template<> inline simu5g::RlcUmRxWindowDesc *fromAnyPtr(any_ptr ptr) { return ptr.get<simu5g::RlcUmRxWindowDesc>(); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_LTERLCDEFS_M_H

